Repository krahyor/frontend_camhub, pull requests merged in 2025-09, with the labels that each got.

#20 ระบบแผนที่ + นำทาง
  android/.gitignore
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/local.defaults.properties
  android/settings.gradle.kts
  lib/models/faculty_destination.dart
  lib/ui/screens/map_screen/map_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend, Update

#30 Maps: Implement location and place destination models with service for fetching locations
  lib/models/faculty_destination.dart
  lib/models/location.dart
  lib/models/place_destination.dart
  lib/ui/screens/map_screen/map_screen.dart
  lib/ui/service/location_service.dart
Labels: frontend, feature

#34 Update Camphub
  lib/core/routes.dart
  lib/main.dart
  lib/models/course.dart
  lib/ui/providers/subject_provider.dart
  lib/ui/screens/account_screen/login_screen.dart
  lib/ui/screens/annoucement_screen/bookmarked_announcements_screen.dart
  lib/ui/screens/example_info_screen/example_info_screen.dart
  lib/ui/screens/home_screen/home_screen.dart
  lib/ui/screens/main_screen/main_screen.dart
  lib/ui/screens/profile_screen/profile_screen.dart
  lib/ui/screens/subject_screen/edit_subject_screen.dart
  lib/ui/screens/subject_screen/subject_screen.dart
  lib/ui/screens/subject_screen/take_subject_screen.dart
Labels: frontend, feature, Fix

#36 feat: implement login requirement for bookmarking and protected screens
  android/app/src/main/AndroidManifest.xml
  lib/ui/providers/events_provider.dart
  lib/ui/screens/annoucement_screen/announcement_detail_screen.dart
  lib/ui/screens/annoucement_screen/announcements_screen.dart
  lib/ui/screens/events_screen/events_screen.dart
  lib/ui/screens/home_screen/home_screen.dart
  lib/ui/screens/main_screen/main_screen.dart
  lib/ui/screens/schedule_screen/schedule_screen.dart
Labels: frontend, feature
